[tool.poetry]
name = "beri"
version = "0.1.0"
description = ""
authors = ["RAG-home <rgilmore@umc.edu>"]

[tool.poetry.dependencies]
python = "*"
click = "^6.7"
rpy2 = "^2.9"
cookiecutter = "^1.6"
pipenv = "^11.10"
pipwin = "^0.4.3"
toml = "^0.9.4"

[tool.poetry.dev-dependencies]
pytest = "^3.5"
