[tool.poetry]
name = "beri"
version = "0.1.0"
description = ""
authors = ["RAG-home <rgilmore@umc.edu>"]

[tool.poetry.dependencies]
python = "*"
click = "^6.7"

[tool.poetry.dev-dependencies]
pytest = "^3.5"
